language: node_js

cache: npm

node_js:
  - 'lts/*'

env:
  - GATSBY_TELEMETRY_DISABLED=1

matrix:
  fast_finish: true

before_script:
  - npm i -g gatsby
  - npm i

script:
  - npm run lint
  - npm run remark-lint
  - npm run build
