language: node_js

cache: yarn

node_js:
  - 'lts/*'

env:
  - GATSBY_TELEMETRY_DISABLED=1

matrix:
  fast_finish: true

before_script:
  - yarn global add gatsby
  - yarn install

script:
  - yarn run lint
  - yarn run remark-lint
  - yarn run build
