language: node_js

os:
  - linux

cache:
  directories:
    - node_modules

node_js:
  - 'stable'

env:
  - GATSBY_TELEMETRY_DISABLED=1

before_script:
  - npm i -g gatsby
  - npm i

script:
  - npm run lint
  - npm run remark-lint
  - npm run build
