name: Build
on:
  pull_request:
    types: [opened, reopened]
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: 17

      - name: Build site
        run: |
          yarn install
          yarn build
